# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-07-09 09:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userenterprise',
            unique_together=set([('user', 'enterprise')]),
        ),
    ]
